### ISSUE TITLE
How can I get "xpubYOUR_XPUB_KEY_GOES_HERE"  AND  "extkey_next_receiving_address"  ?

### ISSUE THREAD

**Issue by Mohammad-Reza-Rahimi-Zade** [coinables/Simple-Barebone-Bitcoin-Paywall#1]
hi

How can I get "xpubYOUR_XPUB_KEY_GOES_HERE"  AND  "extkey_next_receiving_address"  ?

**Comment by coinables** [comment]
Do not change `extkey_next_receiving_address`. 
Your xpub comes from your wallet. Xpubs are extended public keys created from an HD (Hierarchical Deterministic) wallet design following BIP32.
